const $=id=>document.getElementById(id);
const storeKey="aetherisRoomV3";
const selfId=sessionStorage.aetherisSelfId||(sessionStorage.aetherisSelfId=(crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())));
const names=["아르카","노바","카이","루나","제드","이온","베가","리오"];
const selfName=sessionStorage.aetherisName||(sessionStorage.aetherisName=names[Math.floor(Math.random()*names.length)]+Math.floor(Math.random()*90+10));
const elements={
fire:{name:"불",color:0xff4d37,dash:"화염 돌진",jump:"폭염 점프",cards:[c("파이어카드","공격",18,1,16,{burn:5}),c("불기둥카드","방어",24,4,0,{shield:28,burn:3}),c("섬광카드","CC기",26,5,8,{stun:1}),c("플레어카드","궁극기",70,9,42,{burn:10})]},
water:{name:"물",color:0x38a8ff,dash:"물결 활주",jump:"분수 점프",cards:[c("워터샷카드","공격",16,1,13,{slow:1}),c("해일방패카드","방어",24,4,0,{shield:22,heal:12}),c("빙결카드","CC기",30,5,7,{stun:1.4}),c("심해폭포카드","궁극기",70,9,34,{heal:24,slow:2})]},
lightning:{name:"번개",color:0xffe34a,dash:"전광 대쉬",jump:"뇌전 도약",cards:[c("스파크카드","공격",20,.8,18,{}),c("전류막카드","방어",24,4,6,{shield:18}),c("감전카드","CC기",28,4.8,10,{stun:1.2}),c("낙뢰심판카드","궁극기",76,9.5,52,{stun:.8})]},
earth:{name:"땅",color:0xb87939,dash:"암석 돌진",jump:"지진 점프",cards:[c("돌탄카드","공격",15,1.2,14,{}),c("석벽카드","방어",22,3.8,0,{shield:42}),c("균열카드","CC기",28,5.5,9,{stun:1.1}),c("산맥강타카드","궁극기",70,9.5,38,{shield:20,stun:.8})]},
wind:{name:"바람",color:0x35f2cd,dash:"질풍 대쉬",jump:"상승기류 점프",cards:[c("풍탄카드","공격",12,.65,10,{}),c("회오리막카드","방어",20,3.5,0,{shield:20,speed:4}),c("태풍속박카드","CC기",26,4.8,8,{slow:2.2}),c("허리케인카드","궁극기",66,8.5,34,{slow:2.8})]},
light:{name:"빛",color:0xfff4a6,dash:"광휘 이동",jump:"천상 도약",cards:[c("빛탄카드","공격",15,1,12,{heal:4}),c("성역카드","방어",28,4.4,0,{shield:18,heal:18}),c("눈부심카드","CC기",28,5.2,6,{stun:1}),c("천벌광선카드","궁극기",72,9,35,{heal:28})]},
darkness:{name:"어둠",color:0xa66cff,dash:"그림자 이동",jump:"공허 도약",cards:[c("암흑탄카드","공격",17,1.1,14,{drain:.35}),c("그림자막카드","방어",24,4,0,{shield:24,drain:.2}),c("공포카드","CC기",30,5.3,8,{stun:1.3}),c("블랙홀카드","궁극기",74,9.2,40,{drain:.55,slow:2.5})]},
poison:{name:"독",color:0x58e35b,dash:"독안개 대쉬",jump:"맹독 점프",cards:[c("독침카드","공격",14,1,9,{poison:6}),c("부식막카드","방어",22,3.8,0,{shield:20,poison:4}),c("마비독카드","CC기",28,5,6,{stun:.9,poison:8}),c("역병구름카드","궁극기",68,8.8,28,{poison:18,slow:2.4})]}
};
const elementKeys=Object.keys(elements);
const rewardTable={2:[10,6],3:[10,5,3],4:[10,5,3,1]};
let roomCode="",scene,camera,renderer,clock,playerBody,floor,opponentMeshes={},selfVisual=null,effects=[],keys={},mouseLocked=false,gameLoop=0,roomLoop=0,selectedCard=0,lastSync=0,lastHit=0,upgradePicked=false,local={hp:100,maxHp:100,shield:0,mana:30,maxMana:100,pos:{x:0,y:2,z:8},rot:{x:0,y:0},vel:{x:0,y:0,z:0},cooldowns:[0,0,0,0],alive:true,element:"",charge:false,slowUntil:0,stunUntil:0,speedUntil:0,power:1,move:1,cdMul:1,evolve:0,crowns:0,coinBonus:0,devil:false,team:0,coins:0,secondaryElements:[]};
function c(name,type,mana,cd,damage,extra){return{name,type,mana,cd,damage,...extra}}
function readStore(){try{return JSON.parse(localStorage.getItem(storeKey))||{}}catch{return{}}}
function writeStore(s){localStorage.setItem(storeKey,JSON.stringify(s))}
function getRoom(){return readStore()[roomCode]}
function saveRoom(r){const s=readStore();s[r.code]=r;writeStore(s)}
function code(){const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>a[Math.floor(Math.random()*a.length)]).join("")}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function now(){return Date.now()}
function playerBase(x,z){return{id:selfId,name:selfName,hp:100,maxHp:100,shield:0,mana:30,maxMana:100,pos:{x,y:2,z},rot:{x:0,y:0},alive:true,element:"",ready:false,team:0,coins:0,totalCoins:0,wins:0,kills:0,power:1,move:1,cdMul:1,evolve:0,crowns:0,coinBonus:0,devil:false,secondaryElements:[],hitId:0,lastSeen:now(),upgradeReady:false,rank:0}}
function patch(p){const r=getRoom();if(!r||!r.players[selfId])return;r.players[selfId]={...r.players[selfId],...p,lastSeen:now()};saveRoom(r)}
function patchLocal(p){Object.assign(local,p);patch(p)}
function showOnly(id){["menu","lobby","selectScreen","upgradeScreen","hud","endScreen"].forEach(x=>$(x).classList.toggle("hidden",x!==id))}
function message(id,text){$(id).textContent=text}
function log(text){const el=document.createElement("div");el.textContent="> "+text;$("log").appendChild(el);while($("log").children.length>8)$("log").firstChild.remove()}
$("centerStart").onclick=()=>{$("centerStart").classList.add("hidden");$("roomPanel").classList.remove("hidden")};
$("openJoin").onclick=()=>$("joinForm").classList.toggle("hidden");
$("createRoom").onclick=()=>{const maxPlayers=clamp(parseInt($("maxPlayers").value)||2,2,4),maxRounds=clamp(parseInt($("roundCount").value)||8,8,20),mode=$("gameMode").value,room={code:code(),host:selfId,maxPlayers,maxRounds,mode,phase:"lobby",round:1,deadline:0,players:{},logs:[],created:now(),upgradeSeed:0};room.players[selfId]=playerBase(-4,8);roomCode=room.code;saveRoom(room);enterLobby(room.code)};
$("joinForm").onsubmit=e=>{e.preventDefault();const v=$("joinCode").value.trim().toUpperCase();const s=readStore(),r=s[v];if(!r){message("menuMessage","존재하지 않는 참여 코드입니다.");return}if(r.phase!=="lobby"){message("menuMessage","이미 시작된 방입니다.");return}if(Object.keys(r.players).length>=r.maxPlayers&&!r.players[selfId]){message("menuMessage","방이 가득 찼습니다.");return}roomCode=v;r.players[selfId]=r.players[selfId]||playerBase(4,-8);saveRoom(r);enterLobby(v)};
$("startRoom").onclick=()=>{const r=getRoom();if(!r||r.host!==selfId||Object.keys(r.players).length<2)return;assignTeams(r);r.phase="select";r.deadline=now()+10000;Object.values(r.players).forEach(p=>{p.ready=false;p.element=""});saveRoom(r);showSelect()};
function enterLobby(c){roomCode=c;$("roomCode").textContent="참여 코드 "+c;$("roomCode").classList.remove("hidden");showOnly("lobby");clearInterval(roomLoop);roomLoop=setInterval(tickRoom,180);tickLobby()}
function assignTeams(r){const ids=Object.keys(r.players).sort(()=>Math.random()-.5);ids.forEach((id,i)=>r.players[id].team=r.mode==="team"?i%2+1:0)}
function tickLobby(){const r=getRoom();if(!r)return;$("lobbyInfo").textContent=`${r.mode==="team"?"랜덤팀전":"개인전"} · 최대 ${r.maxPlayers}명 · ${r.maxRounds}라운드`;$('lobbyPlayers').innerHTML=Object.values(r.players).map(p=>`<div class="player-row"><span>${p.name}${p.id===r.host?" · 방장":""}</span><b>${p.team?"팀 "+p.team:"대기"}</b></div>`).join("");const canStart=r.host===selfId&&Object.keys(r.players).length>=2;$("startRoom").classList.toggle("hidden",!canStart);message("lobbyMessage",Object.keys(r.players).length<2?"상대가 들어와야 시작할 수 있습니다.":r.host===selfId?"2명 이상 입장했습니다. 시작할 수 있습니다.":"방장이 시작하면 능력 선택으로 넘어갑니다.")}
function tickRoom(){const r=getRoom();if(!r)return;if(r.phase==="lobby"){tickLobby();return}if(r.phase==="select"&&!$("selectScreen").classList.contains("hidden"))tickSelect();if(r.phase==="select"&&$("selectScreen").classList.contains("hidden"))showSelect();if(r.phase==="battle"&&$("hud").classList.contains("hidden"))startBattle(false);if(r.phase==="upgrade"&&$("upgradeScreen").classList.contains("hidden"))showUpgrade();if(r.phase==="end"&&$("endScreen").classList.contains("hidden"))showEnd();if(r.host===selfId)hostTick(r)}
function hostTick(r){const ids=Object.keys(r.players);if(r.phase==="select"){if(ids.every(id=>r.players[id].ready)||now()>r.deadline){ids.forEach((id,i)=>{if(!r.players[id].element)r.players[id].element=elementKeys[(Math.floor(Math.random()*elementKeys.length)+i)%elementKeys.length];r.players[id].ready=true});startRoundState(r)}}else if(r.phase==="battle"){const alive=ids.filter(id=>r.players[id].alive&&r.players[id].hp>0);let done=false;if(r.mode==="team"){const teams=[...new Set(alive.map(id=>r.players[id].team))];done=teams.length<=1}else done=alive.length<=1;if(done||now()>r.deadline){finishRound(r)}}else if(r.phase==="upgrade"){const waiting=ids.some(id=>!r.players[id].upgradeReady);if(!waiting&&r.nextStartAt&&now()>r.nextStartAt)startRoundState(r)}}
function startRoundState(r){const sp=[[-8,8],[8,-8],[-8,-8],[8,8]];Object.keys(r.players).forEach((id,i)=>{const p=r.players[id],s=sp[i%sp.length];p.hp=p.maxHp;p.shield=0;p.mana=30;p.pos={x:s[0],y:2,z:s[1]};p.alive=true;p.ready=true;p.upgradeReady=false;p.rank=0;p.cooldowns=[0,0,0,0];p.hitId=p.hitId||0});r.phase="battle";r.deadline=now()+70000;saveRoom(r)}
function finishRound(r){const ids=Object.keys(r.players);const ranking=ids.sort((a,b)=>{const pa=r.players[a],pb=r.players[b];if(pa.alive!==pb.alive)return pa.alive?-1:1;return pb.hp-pa.hp});const rewards=rewardTable[ids.length]||rewardTable[4];ranking.forEach((id,i)=>{const p=r.players[id],gain=(rewards[i]||1)+(p.coinBonus||0);p.coins+=gain;p.totalCoins+=gain;p.rank=i+1;if(i===0)p.wins++});if(r.round>=r.maxRounds){r.phase="end"}else{r.round++;r.phase=r.round%2===1?"upgrade":"battle";if(r.phase==="upgrade"){r.upgradeSeed=Math.floor(Math.random()*999999);r.nextStartAt=0;Object.values(r.players).forEach(p=>p.upgradeReady=false)}else startRoundState(r)}saveRoom(r)}
function showSelect(){showOnly("selectScreen");buildElementChoices();tickSelect()}
function buildElementChoices(){const box=$("elements");box.innerHTML="";Object.entries(elements).forEach(([id,e])=>{const d=document.createElement("div");d.className="choice";d.style.borderColor="#"+e.color.toString(16).padStart(6,"0");d.innerHTML=`<h3>${e.name}</h3><p>${e.cards.map(x=>x.name).join(" · ")}</p><span class="tag">${e.dash} / ${e.jump}</span>`;d.onclick=()=>chooseElement(id,d);box.appendChild(d)})}
function chooseElement(id,node){document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));node.classList.add("selected");local.element=id;patch({element:id,ready:true});tickSelect()}
function tickSelect(){const r=getRoom();if(!r)return;$("selectTimer").textContent=Math.max(0,Math.ceil((r.deadline-now())/1000));$("selectStatus").textContent=Object.values(r.players).map(p=>`${p.name}: ${p.element?elements[p.element].name:"선택 중"}`).join(" · ")}
function showUpgrade(){showOnly("upgradeScreen");upgradePicked=false;const r=getRoom();const p=r.players[selfId];$("upgradeTitle").textContent=`${r.round-1}라운드 종료 보상 선택`;$("upgradeDesc").textContent="하나만 선택할 수 있습니다. 선택한 뒤 모두 선택하면 3초 후 다음 전투가 시작됩니다.";buildUpgradeOptions(p,r)}
function rng(seed){let x=Math.sin(seed)*10000;return x-Math.floor(x)}
function sample(arr,n,seed){const a=[...arr],out=[];for(let i=0;i<n&&a.length;i++){const k=Math.floor(rng(seed+i*91)*a.length);out.push(a.splice(k,1)[0])}return out}
function dedicatedCard(p,seed){const e=elements[p.element||"fire"],rare=rng(seed)>0.72,base=e.cards[Math.floor(rng(seed+7)*e.cards.length)];return{kind:"dedicated",title:rare?`희귀 전용 ${base.name}`:`전용 ${base.name}`,desc:rare?`${base.name} 피해와 효과가 크게 증가합니다.`:`${base.name} 성능이 증가합니다.`,apply:q=>{q.power+=rare?.18:.1;q.coins=Math.max(0,q.coins-(rare?5:3))},cost:rare?5:3}}
function buildUpgradeOptions(p,r){const common=[
{kind:"move",title:"이속증가",desc:"이동 속도 12% 증가",cost:2,apply:q=>{q.move+=.12}},
{kind:"power",title:"능력증폭",desc:"카드 피해와 회복 12% 증가",cost:3,apply:q=>{q.power+=.12}},
{kind:"hp",title:"체력증가",desc:"최대 체력 18 증가",cost:3,apply:q=>{q.maxHp+=18;q.hp=q.maxHp}},
{kind:"cool",title:"쿨타임감소",desc:"전체 카드 쿨타임 8% 감소",cost:3,apply:q=>{q.cdMul*=.92}},
{kind:"coin",title:"추가 코인 증가",desc:"매 라운드 보상 코인 +1",cost:4,apply:q=>{q.coinBonus+=1}},
{kind:"evolve",title:"진화",desc:"5번 강화하면 최종 진화 카드로 변경",cost:5,apply:q=>{q.evolve+=1;if(q.evolve>=5){q.power+=.45;q.maxHp+=35;q.hp=q.maxHp}}},
{kind:"crown",title:"왕관",desc:"7번 구매하면 악마의 카드로 변환",cost:6,apply:q=>{q.crowns+=1;if(q.crowns>=7&&!q.devil){q.devil=true;q.power+=.55;q.maxHp+=30;q.hp=q.maxHp}}},
{kind:"other",title:"랜덤 다른 능력카드",desc:"다른 원소를 보조 능력으로 흡수하고 주변 장식으로 표시",cost:4,apply:q=>{const pool=elementKeys.filter(x=>x!==q.element&&!(q.secondaryElements||[]).includes(x));const pick=pool[Math.floor(Math.random()*pool.length)]||elementKeys[0];q.secondaryElements=[...(q.secondaryElements||[]),pick].slice(-3);q.power+=.08;q.maxMana+=10}}
];
const options=sample(common,3,r.upgradeSeed+parseInt(selfId.replace(/\D/g,"").slice(0,5)||"7"));if(rng(r.upgradeSeed+99)>.58)options[Math.floor(rng(r.upgradeSeed+13)*options.length)]=dedicatedCard(p,r.upgradeSeed+23);const box=$("upgradeOptions");box.innerHTML="";options.forEach(o=>{const d=document.createElement("div");d.className="upgrade-card";d.innerHTML=`<h3>${o.title}</h3><p>${o.desc}</p><span class="tag">가격 ${o.cost}코인 · 보유 ${p.coins}코인</span>`;d.onclick=()=>pickUpgrade(o,d);box.appendChild(d)})}
function pickUpgrade(o,node){if(upgradePicked)return;const r=getRoom(),p=r.players[selfId];if(!p||p.coins<o.cost){message("upgradeStatus","코인이 부족합니다.");return}o.apply(p);p.coins-=o.cost;p.upgradeReady=true;r.players[selfId]=p;if(Object.values(r.players).every(x=>x.upgradeReady))r.nextStartAt=now()+3000;saveRoom(r);upgradePicked=true;document.querySelectorAll(".upgrade-card").forEach(x=>x.classList.remove("selected"));node.classList.add("selected");message("upgradeStatus","선택 완료. 모두 선택하면 3초 뒤 전투가 시작됩니다.")}
function startBattle(fresh=true){showOnly("hud");const r=getRoom(),p=r.players[selfId];Object.assign(local,{hp:p.hp,maxHp:p.maxHp,shield:p.shield,mana:p.mana,maxMana:p.maxMana,pos:p.pos,element:p.element,team:p.team,coins:p.coins,power:p.power,move:p.move,cdMul:p.cdMul,evolve:p.evolve,crowns:p.crowns,devil:p.devil,secondaryElements:p.secondaryElements||[],alive:true,cooldowns:[0,0,0,0],vel:{x:0,y:0,z:0}});if(!renderer)init3d();refreshSelfVisual();document.body.requestPointerLock?.();renderCards();log(`${r.round}라운드 시작`);if(!gameLoop)animate()}
function init3d(){scene=new THREE.Scene();scene.background=new THREE.Color(0x070a13);scene.fog=new THREE.Fog(0x070a13,12,80);camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.1,1000);renderer=new THREE.WebGLRenderer({canvas:$("game"),antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));clock=new THREE.Clock();scene.add(new THREE.HemisphereLight(0xffffff,0x152044,1.5));const l=new THREE.DirectionalLight(0xffffff,1.1);l.position.set(5,10,4);scene.add(l);floor=new THREE.Mesh(new THREE.PlaneGeometry(90,90,30,30),new THREE.MeshStandardMaterial({color:0x121a31,wireframe:true}));floor.rotation.x=-Math.PI/2;scene.add(floor);playerBody=new THREE.Object3D();scene.add(playerBody);addArena();addEvents();refreshSelfVisual()}
function addArena(){const ground=new THREE.Mesh(new THREE.CylinderGeometry(31,31,.5,96),new THREE.MeshStandardMaterial({color:0x9a7b55,roughness:.9,metalness:.05}));ground.position.y=-1.28;scene.add(ground);const sand=new THREE.Mesh(new THREE.CircleGeometry(25.5,96),new THREE.MeshStandardMaterial({color:0xc3a06f,roughness:1}));sand.rotation.x=-Math.PI/2;sand.position.y=-.99;scene.add(sand);const wallMat=new THREE.MeshStandardMaterial({color:0x6f604e,roughness:.85});const railMat=new THREE.MeshStandardMaterial({color:0x332a24,roughness:.75});for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(29+i*2.2,.55,8,128),i===0?wallMat:railMat);ring.rotation.x=Math.PI/2;ring.position.y=i*2.2+.15;scene.add(ring)}for(let i=0;i<44;i++){const a=i/44*Math.PI*2,x=Math.cos(a)*29,z=Math.sin(a)*29,h=4.6+(i%3)*.55;const col=new THREE.Mesh(new THREE.CylinderGeometry(.42,.55,h,12),wallMat);col.position.set(x,h/2-1,z);col.rotation.y=-a;scene.add(col);const cap=new THREE.Mesh(new THREE.BoxGeometry(1.5,.35,1.5),railMat);cap.position.set(x,h-0.78,z);cap.rotation.y=-a;scene.add(cap)}for(let i=0;i<20;i++){const a=i/20*Math.PI*2,r=13+Math.random()*8;const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.4+Math.random()*.7,0),new THREE.MeshStandardMaterial({color:0x7b694f,roughness:1}));rock.position.set(Math.cos(a)*r,-.75,Math.sin(a)*r);rock.rotation.set(Math.random(),Math.random(),Math.random());scene.add(rock)}}

function elementColor(id){return elements[id||"fire"].color}
function mat(id,em=.25){const c=elementColor(id);return new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:em,roughness:.5,metalness:.08,transparent:false})}
function disposeObj(o){if(!o)return;o.traverse?.(x=>{if(x.geometry)x.geometry.dispose?.();if(x.material)x.material.dispose?.()});scene.remove(o)}
function makeAvatar(p,self=false){const root=new THREE.Group(),id=p.element||"fire",color=elementColor(id),bodyMat=mat(id,p.devil?.65:.28);let body;if(id==="fire"){body=new THREE.Mesh(new THREE.ConeGeometry(.62,1.95,18),bodyMat);body.position.y=.05}else if(id==="water"){body=new THREE.Mesh(new THREE.SphereGeometry(.72,20,14),bodyMat);body.scale.y=1.45}else if(id==="lightning"){body=new THREE.Mesh(new THREE.OctahedronGeometry(.85,1),bodyMat);body.scale.y=1.55}else if(id==="earth"){body=new THREE.Mesh(new THREE.DodecahedronGeometry(.82,0),bodyMat);body.scale.y=1.35}else if(id==="wind"){body=new THREE.Mesh(new THREE.TorusKnotGeometry(.42,.16,64,8),bodyMat);body.scale.set(1.15,1.7,1.15)}else if(id==="light"){body=new THREE.Mesh(new THREE.IcosahedronGeometry(.78,1),bodyMat);body.scale.y=1.45}else if(id==="darkness"){body=new THREE.Mesh(new THREE.CapsuleGeometry(.48,1.25,8,16),bodyMat);body.scale.y=1.08}else{body=new THREE.Mesh(new THREE.CapsuleGeometry(.44,1.15,8,16),bodyMat);body.scale.y=1.18}root.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.28,16,12),bodyMat);head.position.y=1.25;root.add(head);const ring=new THREE.Mesh(new THREE.TorusGeometry(.9,.035,8,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:self?.42:.65}));ring.rotation.x=Math.PI/2;ring.position.y=-.75;root.add(ring);if(p.devil){const horns=new THREE.Group();[-.2,.2].forEach(x=>{const h=new THREE.Mesh(new THREE.ConeGeometry(.1,.38,8),new THREE.MeshBasicMaterial({color:0x210010}));h.position.set(x,1.62,0);horns.add(h)});root.add(horns)}if(p.evolve>=5){const aura=new THREE.Mesh(new THREE.TorusGeometry(1.12,.045,8,56),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.55}));aura.rotation.x=Math.PI/2;aura.position.y=.6;root.add(aura)};(p.secondaryElements||[]).slice(0,3).forEach((sid,i)=>{const c=elementColor(sid),g=sid==="water"?new THREE.SphereGeometry(.12,10,8):sid==="fire"?new THREE.ConeGeometry(.1,.26,9):sid==="lightning"?new THREE.OctahedronGeometry(.14,0):sid==="earth"?new THREE.DodecahedronGeometry(.14,0):new THREE.SphereGeometry(.11,8,6);const o=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:self?.46:.82}));const a=i*Math.PI*2/3;o.position.set(Math.cos(a)*1.05,.55+i*.18,Math.sin(a)*1.05);o.userData.orbit={base:a,rad:1.05,speed:1.1+i*.35,h:.55+i*.18};root.add(o)});root.userData.element=id;root.userData.secondary=(p.secondaryElements||[]).join(",");root.userData.devil=!!p.devil;root.userData.evolve=p.evolve||0;return root}
function refreshSelfVisual(){if(!scene)return;disposeObj(selfVisual);selfVisual=makeAvatar(local,true);selfVisual.scale.set(.36,.36,.36);scene.add(selfVisual)}
function updateAvatar(root,dt){const t=performance.now()*.001;root.children.forEach(o=>{if(o.userData.orbit){const a=o.userData.orbit.base+t*o.userData.orbit.speed;o.position.x=Math.cos(a)*o.userData.orbit.rad;o.position.z=Math.sin(a)*o.userData.orbit.rad;o.position.y=o.userData.orbit.h+Math.sin(t*2+a)*.08}});root.rotation.y+=dt*.8}
function visualChanged(mesh,p){return mesh.userData.element!==(p.element||"fire")||mesh.userData.secondary!==(p.secondaryElements||[]).join(",")||mesh.userData.devil!==!!p.devil||mesh.userData.evolve!==(p.evolve||0)}

function addEvents(){addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener("keydown",e=>{keys[e.code]=true;if(/^Digit[1-4]$/.test(e.code)){selectedCard=parseInt(e.code.at(-1))-1;renderCards()}});addEventListener("keyup",e=>keys[e.code]=false);addEventListener("mousemove",e=>{if(document.pointerLockElement!==document.body)return;local.rot.y-=e.movementX*.0022;local.rot.x=clamp(local.rot.x-e.movementY*.0022,-1.35,1.35)});addEventListener("mousedown",e=>{if($("hud").classList.contains("hidden"))return;if(document.pointerLockElement!==document.body)document.body.requestPointerLock?.();if(e.button===0)castCard();if(e.button===2)local.charge=true});addEventListener("mouseup",e=>{if(e.button===2)local.charge=false});addEventListener("contextmenu",e=>e.preventDefault())}
function renderCards(){const e=elements[local.element||"fire"],cards=getCards(e);$("cards").innerHTML=cards.map((card,i)=>`<div class="card ${i===selectedCard?"active":""}" style="border-color:#${e.color.toString(16).padStart(6,"0")}"><h4>${card.name}</h4><p>${card.type} · 마나 ${card.mana}<br>${card.damage?"피해 "+Math.round(card.damage*local.power):"보조"} · ${Math.max(.2,card.cd*local.cdMul).toFixed(1)}초</p></div>`).join("")}
function getCards(e){const arr=e.cards.map(x=>({...x}));if(local.evolve>=5)arr[3]={...arr[3],name:"최종진화 " + arr[3].name,damage:Math.round(arr[3].damage*1.75),mana:Math.max(25,arr[3].mana-15),cd:arr[3].cd*.72,shield:(arr[3].shield||0)+25,heal:(arr[3].heal||0)+20};if(local.devil)arr.forEach(x=>{x.name="악마의 "+x.name;x.damage=Math.round((x.damage||0)*1.65);x.drain=(x.drain||.25)+.35;x.mana=Math.max(10,x.mana-8)});return arr}
function animate(){gameLoop=requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);const r=getRoom();if(!r||r.phase!=="battle")return;updateLocal(dt,r);updateOpponents(r);updateEffects(dt);updateHud(r);renderer.render(scene,camera)}
function updateLocal(dt,r){if(!local.alive)return;const t=now();local.cooldowns=local.cooldowns.map(x=>Math.max(0,x-dt));if(local.charge)local.mana=clamp(local.mana+38*dt,0,local.maxMana);else local.mana=clamp(local.mana+10*dt,0,local.maxMana);const stunned=t<local.stunUntil,base=(t<local.speedUntil?9:6.5)*local.move*(t<local.slowUntil?.55:1);let dx=0,dz=0;if(!stunned){if(keys.KeyW)dz-=1;if(keys.KeyS)dz+=1;if(keys.KeyA)dx-=1;if(keys.KeyD)dx+=1}const len=Math.hypot(dx,dz)||1,sy=Math.sin(local.rot.y),cy=Math.cos(local.rot.y);local.vel.x=(dx/len*cy-dz/len*sy)*base;local.vel.z=(dz/len*cy+dx/len*sy)*base;if(keys.ShiftLeft&&!stunned){dash();keys.ShiftLeft=false}if(keys.Space&&local.pos.y<=2.02&&!stunned){jump();keys.Space=false}local.vel.y-=20*dt;local.pos.x=clamp(local.pos.x+local.vel.x*dt,-24,24);local.pos.z=clamp(local.pos.z+local.vel.z*dt,-24,24);local.pos.y+=local.vel.y*dt;if(local.pos.y<2){local.pos.y=2;local.vel.y=0}camera.position.set(local.pos.x,local.pos.y,local.pos.z);if(selfVisual){if(visualChanged(selfVisual,local))refreshSelfVisual();selfVisual.position.set(local.pos.x,local.pos.y-1.55,local.pos.z);selfVisual.rotation.y=local.rot.y;updateAvatar(selfVisual,dt)}camera.rotation.order="YXZ";camera.rotation.y=local.rot.y;camera.rotation.x=local.rot.x;if(t-lastSync>90){patch({hp:local.hp,maxHp:local.maxHp,shield:local.shield,mana:Math.round(local.mana),pos:local.pos,rot:local.rot,alive:local.alive,coins:local.coins,power:local.power,move:local.move,cdMul:local.cdMul,evolve:local.evolve,crowns:local.crowns,devil:local.devil,secondaryElements:local.secondaryElements||[]});lastSync=t}}
function dash(){const e=elements[local.element||"fire"];const sy=Math.sin(local.rot.y),cy=Math.cos(local.rot.y),mul=local.element==="wind"?10:local.element==="earth"?6:8;local.pos.x-=sy*mul;local.pos.z-=cy*mul;if(local.element==="fire")spawn(local.pos,0xff4d37,18);if(local.element==="darkness")local.hp=clamp(local.hp+4,0,local.maxHp);log(e.dash)}
function jump(){const e=elements[local.element||"fire"];local.vel.y=local.element==="wind"?11:local.element==="earth"?7.5:9;if(local.element==="light")local.hp=clamp(local.hp+3,0,local.maxHp);log(e.jump)}
function castCard(){const e=elements[local.element||"fire"],cards=getCards(e),card=cards[selectedCard];if(!card||local.cooldowns[selectedCard]>0||local.mana<card.mana||now()<local.stunUntil)return;local.mana-=card.mana;local.cooldowns[selectedCard]=Math.max(.2,card.cd*local.cdMul);let target=findTarget();if(card.shield)local.shield+=Math.round(card.shield*local.power);if(card.heal)local.hp=clamp(local.hp+Math.round(card.heal*local.power),0,local.maxHp);if(card.speed)local.speedUntil=now()+card.speed*1000;if(target&&card.damage>0)hitTarget(target,card,e);spawn(local.pos,e.color,18);renderCards();log(card.name+" 사용")}
function findTarget(){const r=getRoom();if(!r)return null;let best=null,bd=999;Object.entries(r.players).forEach(([id,p])=>{if(id===selfId||!p.alive||p.hp<=0)return;if(r.mode==="team"&&p.team===local.team)return;const d=Math.hypot(p.pos.x-local.pos.x,p.pos.z-local.pos.z);if(d<bd&&d<42){bd=d;best={id,p,d}}});return best}
function hitTarget(target,card,e){const r=getRoom();if(!r||!r.players[target.id])return;const p=r.players[target.id];let dmg=Math.round((card.damage||0)*local.power);if(p.shield>0){const blocked=Math.min(p.shield,dmg);p.shield-=blocked;dmg-=blocked}p.hp-=dmg;if(card.poison)p.hp-=Math.round(card.poison*local.power);if(card.burn)p.hp-=Math.round(card.burn*local.power);if(card.stun)p.stunUntil=now()+card.stun*1000;if(card.slow)p.slowUntil=now()+card.slow*1000;if(card.drain)local.hp=clamp(local.hp+Math.round((card.damage||8)*card.drain),0,local.maxHp);if(p.hp<=0){p.hp=0;p.alive=false;local.coins+=1;local.kills=(local.kills||0)+1}p.hitId=(p.hitId||0)+1;r.players[target.id]=p;saveRoom(r)}
function updateOpponents(r){Object.entries(r.players).forEach(([id,p])=>{if(id===selfId)return;let mesh=opponentMeshes[id];if(!mesh||visualChanged(mesh,p)){disposeObj(mesh);mesh=makeAvatar(p,false);scene.add(mesh);opponentMeshes[id]=mesh}mesh.visible=p.alive&&p.hp>0;mesh.position.set(p.pos.x,p.pos.y-1,p.pos.z);mesh.rotation.y=p.rot.y;updateAvatar(mesh,.016)});Object.keys(opponentMeshes).forEach(id=>{if(!r.players[id]){disposeObj(opponentMeshes[id]);delete opponentMeshes[id]}});const me=r.players[selfId];if(me){if(me.hitId!==lastHit){lastHit=me.hitId;local.hp=me.hp;local.shield=me.shield;local.stunUntil=me.stunUntil||0;local.slowUntil=me.slowUntil||0;spawn(local.pos,0xff0044,24);if(local.hp<=0){local.alive=false;patch({alive:false,hp:0})}}}} 
function updateEffects(dt){for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;e.mesh.scale.multiplyScalar(1+dt*3);e.mesh.material.opacity=Math.max(0,e.life);if(e.life<=0){scene.remove(e.mesh);effects.splice(i,1)}}}
function spawn(pos,color,count){for(let i=0;i<count;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.08,6,6),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9}));m.position.set(pos.x+(Math.random()-.5)*1.5,pos.y-1+Math.random()*1.5,pos.z+(Math.random()-.5)*1.5);m.userData.v=new THREE.Vector3((Math.random()-.5)*5,Math.random()*3,(Math.random()-.5)*5);scene.add(m);effects.push({mesh:m,life:.5+Math.random()*.4})}}
function updateHud(r){$("hpText").textContent=Math.round(local.hp)+(local.shield?" +"+Math.round(local.shield):"");$("manaText").textContent=Math.round(local.mana);$("roundText").textContent=`${r.round} / ${r.maxRounds}`;$("hpBar").style.width=clamp(local.hp/local.maxHp*100,0,100)+"%";$("manaBar").style.width=clamp(local.mana/local.maxMana*100,0,100)+"%";$("roundBar").style.width=clamp(r.round/r.maxRounds*100,0,100)+"%";$("scoreboard").innerHTML=Object.values(r.players).sort((a,b)=>b.totalCoins-a.totalCoins).map(p=>`<div class="score-line"><span>${p.name}${p.team?" · T"+p.team:""}${p.devil?" · 악마":""}${p.evolve>=5?" · 최종진화":""}</span><b>${p.hp>0?Math.round(p.hp):"탈락"} HP · ${p.coins}C</b></div>`).join("")}
function showEnd(){showOnly("endScreen");const r=getRoom();if(!r)return;$("finalScores").innerHTML=Object.values(r.players).sort((a,b)=>b.totalCoins-a.totalCoins).map((p,i)=>`<div class="player-row"><span>${i+1}위 ${p.name}${p.team?" · 팀 "+p.team:""}</span><b>${p.totalCoins} 코인 · 승리 ${p.wins}</b></div>`).join("")}
